"""Guard against silent CI death when the canonical branch drifts.

The CI workflow at ``.github/workflows/ci.yml`` only runs on pushes and
pull_requests that target the local canonical branch. If someone renames
the branch (or writes the workflow against the wrong name), CI silently
stops triggering and the next push is never validated.

This test parses the workflow YAML and asserts that **every** ``branches:``
filter equals the canonical branch reported by ``git rev-parse
--abbrev-ref HEAD``. A failure here is a loud, local signal that CI is
about to die — fix it before pushing.

Tracked in Kanban task ``t_d04abbd1`` (gap-G, CI branch-filter fix).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = REPO_ROOT / ".github" / "workflows" / "ci.yml"


def _canonical_branch() -> str:
    """Return the canonical branch as ``git`` sees it locally."""
    out = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    branch = out.stdout.strip()
    assert branch, "git rev-parse returned empty branch"
    assert branch != "HEAD", (
        f"Repository is in detached HEAD state; cannot determine canonical "
        f"branch for CI branch-filter guard. Detach was: {branch!r}"
    )
    return branch


def _parse_branch_filters(workflow_text: str) -> list[list[str]]:
    """Return every ``branches:`` list under ``on:`` in the workflow.

    Uses a lightweight regex parser instead of pulling in ``pyyaml`` —
    the workflow file is generated by humans and the ``branches:`` key
    is always inline (we don't recurse into ``jobs.`` or arbitrary
    mapping structures).
    """
    # Match `branches: [a, b, c]` (inline flow style).
    inline = re.findall(r"^\s*branches:\s*\[([^\]]+)\]", workflow_text, re.MULTILINE)
    # Match `branches:\n  - a\n  - b` (block style, indented continuation lines).
    block_matches: list[list[str]] = []
    for match in re.finditer(
        r"^\s*branches:\s*\n((?:\s+-\s+\S+\s*\n)+)",
        workflow_text,
        re.MULTILINE,
    ):
        items = re.findall(r"-\s+(\S+)", match.group(1))
        if items:
            block_matches.append(items)
    inline_matches = [[s.strip() for s in item.split(",") if s.strip()] for item in inline]
    return inline_matches + block_matches


def test_ci_workflow_targets_canonical_branch() -> None:
    """The CI workflow's push and pull_request triggers must target the
    canonical branch. Anything else means CI silently never runs.
    """
    assert WORKFLOW_PATH.exists(), f"Workflow file not found: {WORKFLOW_PATH}"
    canonical = _canonical_branch()
    workflow_text = WORKFLOW_PATH.read_text(encoding="utf-8")

    branch_filters = _parse_branch_filters(workflow_text)
    assert branch_filters, (
        "No `branches:` filter found in ci.yml — CI is unconstrained or "
        "the parser missed a new syntax. Add an explicit branch filter."
    )

    mismatched = [f for f in branch_filters if canonical not in f]
    assert not mismatched, (
        f"CI workflow triggers do not include the canonical branch "
        f"{canonical!r}. Found branch filters: {branch_filters!r}. "
        f"CI will never run on pushes/PRs to the real canonical branch."
    )


def test_ci_workflow_preserves_minimal_permissions() -> None:
    """``permissions: contents: read`` must remain in the workflow.

    The Community Edition CI does not need write access; broadening
    permissions is a security regression and out of scope for any
    branch-filter fix.
    """
    workflow_text = WORKFLOW_PATH.read_text(encoding="utf-8")
    # Match either inline (`contents: read`) or block style.
    assert re.search(r"^\s*contents:\s*read\s*$", workflow_text, re.MULTILINE), (
        "ci.yml is missing `contents: read` permission — broadening "
        "permissions is out of scope for this task."
    )


def test_ci_workflow_python_matrix_intact() -> None:
    """The Python 3.11/3.12/3.13 matrix must remain in the workflow.

    Any change here changes the supported Python versions — a separate
    decision, not part of a branch-filter fix.
    """
    workflow_text = WORKFLOW_PATH.read_text(encoding="utf-8")
    for version in ("3.11", "3.12", "3.13"):
        assert f'"{version}"' in workflow_text, (
            f"Python {version} missing from ci.yml matrix — matrix "
            f"mutation is out of scope for this task."
        )


if __name__ == "__main__":
    # Allow running the guard without pytest installed for quick local checks.
    import sys

    sys.exit(pytest.main([__file__, "-v"]))
